max_clauses(6)
max_body(5)
max_vars(6)
head_pred(drive,4).
body_pred(init_at,3).
body_pred(init_on,3).
body_pred(init_available,2).
body_pred(init_clear,2).
body_pred(goal_on,3).
type(drive,(truck,depot,depot,problem));
type(drive,(truck,depot,distributor,problem));
type(drive,(truck,depot,place,problem));
type(drive,(truck,distributor,depot,problem));
type(drive,(truck,distributor,distributor,problem));
type(drive,(truck,distributor,place,problem));
type(drive,(truck,place,depot,problem));
type(drive,(truck,place,distributor,problem));
type(drive,(truck,place,place,problem)).
type(init_at,(truck,depot,problem));
type(init_at,(truck,distributor,problem));
type(init_at,(truck,place,problem));
type(init_at,(hoist,depot,problem));
type(init_at,(hoist,distributor,problem));
type(init_at,(hoist,place,problem));
type(init_at,(pallet,depot,problem));
type(init_at,(pallet,distributor,problem));
type(init_at,(pallet,place,problem));
type(init_at,(crate,depot,problem));
type(init_at,(crate,distributor,problem));
type(init_at,(crate,place,problem));
type(init_at,(surface,depot,problem));
type(init_at,(surface,distributor,problem));
type(init_at,(surface,place,problem));
type(init_at,(locatable,depot,problem));
type(init_at,(locatable,distributor,problem));
type(init_at,(locatable,place,problem)).
type(init_on,(crate,pallet,problem));
type(init_on,(crate,crate,problem));
type(init_on,(crate,surface,problem)).
type(init_available,(hoist,problem)).
type(init_clear,(pallet,problem));
type(init_clear,(crate,problem));
type(init_clear,(surface,problem)).
type(goal_on,(crate,pallet,problem));
type(goal_on,(crate,crate,problem));
type(goal_on,(crate,surface,problem)).
direction(drive,(out,out,out,in)).
direction(init_at,(out,out,in)).
direction(init_on,(out,out,in)).
direction(init_available,(out,in)).
direction(init_clear,(out,in)).
direction(goal_on,(out,out,in)).
